/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.Timetable;

import app.Connector;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import app.Timetable.Class;
import javax.swing.BoxLayout;

/**
 *
 * @author boywithuke
 */
public class Window_Main extends javax.swing.JFrame {

    /**
     * Creates new form Window_Main
     */
    private String classe;

    public Window_Main(String classe) {
        initComponents();

        setResizable(false);
        setLocationRelativeTo(null);
        this.classe = classe;
        setNameLabelText(this.classe);
        getPlageFromDatabase(Name_Label.getText());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MondayIFrame = new javax.swing.JInternalFrame();
        MondayLabel = new javax.swing.JLabel();
        MondayMorningPanel = new javax.swing.JPanel();
        MondayEveningPanel = new javax.swing.JPanel();
        TuesdayIFrame = new javax.swing.JInternalFrame();
        TuesdayLabel = new javax.swing.JLabel();
        TuesdayMorningPanel = new javax.swing.JPanel();
        TuesdayEveningPanel = new javax.swing.JPanel();
        MondayIFrame3 = new javax.swing.JInternalFrame();
        TuesdayLabel1 = new javax.swing.JLabel();
        ThursdayMorningPanel = new javax.swing.JPanel();
        ThursdayEveningPanel = new javax.swing.JPanel();
        WednesdayIFrame = new javax.swing.JInternalFrame();
        WednesdayLabel = new javax.swing.JLabel();
        WednesdayMorningPanel = new javax.swing.JPanel();
        WednesdayEveningPanel = new javax.swing.JPanel();
        MondayIFrame5 = new javax.swing.JInternalFrame();
        MondayLabel2 = new javax.swing.JLabel();
        FridayMorningPanel = new javax.swing.JPanel();
        FridayEveningPanel = new javax.swing.JPanel();
        MondayIFrame4 = new javax.swing.JInternalFrame();
        TuesdayLabel2 = new javax.swing.JLabel();
        SaturdayMorningPanel = new javax.swing.JPanel();
        SaturdayEveningPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        Name_Label = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ButtonAdd = new javax.swing.JButton();
        ButtonDelete = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(31, 35, 44));
        setMaximumSize(new java.awt.Dimension(2147483647, 214748347));

        jPanel1.setBackground(new java.awt.Color(19, 21, 25));

        MondayIFrame.setVisible(true);

        MondayLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MondayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MondayLabel.setText("MONDAY");

        MondayMorningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout MondayMorningPanelLayout = new javax.swing.GroupLayout(MondayMorningPanel);
        MondayMorningPanel.setLayout(MondayMorningPanelLayout);
        MondayMorningPanelLayout.setHorizontalGroup(
            MondayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        MondayMorningPanelLayout.setVerticalGroup(
            MondayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        MondayMorningPanel.setPreferredSize(new Dimension(240, 321));
        MondayMorningPanel.setLayout(new BoxLayout(MondayMorningPanel, BoxLayout.Y_AXIS));

        MondayEveningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout MondayEveningPanelLayout = new javax.swing.GroupLayout(MondayEveningPanel);
        MondayEveningPanel.setLayout(MondayEveningPanelLayout);
        MondayEveningPanelLayout.setHorizontalGroup(
            MondayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        MondayEveningPanelLayout.setVerticalGroup(
            MondayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        MondayEveningPanel.setPreferredSize(new Dimension(240, 321));
        MondayEveningPanel.setLayout(new BoxLayout(MondayEveningPanel, BoxLayout.Y_AXIS));

        javax.swing.GroupLayout MondayIFrameLayout = new javax.swing.GroupLayout(MondayIFrame.getContentPane());
        MondayIFrame.getContentPane().setLayout(MondayIFrameLayout);
        MondayIFrameLayout.setHorizontalGroup(
            MondayIFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayIFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MondayIFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MondayIFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MondayLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MondayMorningPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MondayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MondayIFrameLayout.setVerticalGroup(
            MondayIFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayIFrameLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MondayLabel)
                .addGap(18, 18, 18)
                .addComponent(MondayMorningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MondayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        TuesdayIFrame.setVisible(true);

        TuesdayLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TuesdayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TuesdayLabel.setText("TUESDAY");

        TuesdayMorningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout TuesdayMorningPanelLayout = new javax.swing.GroupLayout(TuesdayMorningPanel);
        TuesdayMorningPanel.setLayout(TuesdayMorningPanelLayout);
        TuesdayMorningPanelLayout.setHorizontalGroup(
            TuesdayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        TuesdayMorningPanelLayout.setVerticalGroup(
            TuesdayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        TuesdayMorningPanel.setPreferredSize(new Dimension(240, 321));
        TuesdayMorningPanel.setLayout(new BoxLayout(TuesdayMorningPanel, BoxLayout.Y_AXIS));

        TuesdayEveningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout TuesdayEveningPanelLayout = new javax.swing.GroupLayout(TuesdayEveningPanel);
        TuesdayEveningPanel.setLayout(TuesdayEveningPanelLayout);
        TuesdayEveningPanelLayout.setHorizontalGroup(
            TuesdayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        TuesdayEveningPanelLayout.setVerticalGroup(
            TuesdayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        TuesdayEveningPanel.setPreferredSize(new Dimension(240, 321));
        TuesdayEveningPanel.setLayout(new BoxLayout(TuesdayEveningPanel, BoxLayout.Y_AXIS));

        javax.swing.GroupLayout TuesdayIFrameLayout = new javax.swing.GroupLayout(TuesdayIFrame.getContentPane());
        TuesdayIFrame.getContentPane().setLayout(TuesdayIFrameLayout);
        TuesdayIFrameLayout.setHorizontalGroup(
            TuesdayIFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TuesdayIFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TuesdayIFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TuesdayMorningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TuesdayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TuesdayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TuesdayIFrameLayout.setVerticalGroup(
            TuesdayIFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TuesdayIFrameLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TuesdayLabel)
                .addGap(18, 18, 18)
                .addComponent(TuesdayMorningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TuesdayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        MondayIFrame3.setVisible(true);

        TuesdayLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TuesdayLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TuesdayLabel1.setText("THURSDAY");

        ThursdayMorningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout ThursdayMorningPanelLayout = new javax.swing.GroupLayout(ThursdayMorningPanel);
        ThursdayMorningPanel.setLayout(ThursdayMorningPanelLayout);
        ThursdayMorningPanelLayout.setHorizontalGroup(
            ThursdayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        ThursdayMorningPanelLayout.setVerticalGroup(
            ThursdayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        ThursdayMorningPanel.setPreferredSize(new Dimension(240, 321));
        ThursdayMorningPanel.setLayout(new BoxLayout(ThursdayMorningPanel, BoxLayout.Y_AXIS));

        ThursdayEveningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout ThursdayEveningPanelLayout = new javax.swing.GroupLayout(ThursdayEveningPanel);
        ThursdayEveningPanel.setLayout(ThursdayEveningPanelLayout);
        ThursdayEveningPanelLayout.setHorizontalGroup(
            ThursdayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        ThursdayEveningPanelLayout.setVerticalGroup(
            ThursdayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        ThursdayEveningPanel.setPreferredSize(new Dimension(240, 321));
        ThursdayEveningPanel.setLayout(new BoxLayout(ThursdayEveningPanel, BoxLayout.Y_AXIS));

        javax.swing.GroupLayout MondayIFrame3Layout = new javax.swing.GroupLayout(MondayIFrame3.getContentPane());
        MondayIFrame3.getContentPane().setLayout(MondayIFrame3Layout);
        MondayIFrame3Layout.setHorizontalGroup(
            MondayIFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayIFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MondayIFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ThursdayMorningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThursdayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TuesdayLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        MondayIFrame3Layout.setVerticalGroup(
            MondayIFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayIFrame3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TuesdayLabel1)
                .addGap(18, 18, 18)
                .addComponent(ThursdayMorningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(ThursdayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        WednesdayIFrame.setVisible(true);

        WednesdayLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        WednesdayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WednesdayLabel.setText("WEDNESDAY");

        WednesdayMorningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout WednesdayMorningPanelLayout = new javax.swing.GroupLayout(WednesdayMorningPanel);
        WednesdayMorningPanel.setLayout(WednesdayMorningPanelLayout);
        WednesdayMorningPanelLayout.setHorizontalGroup(
            WednesdayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        WednesdayMorningPanelLayout.setVerticalGroup(
            WednesdayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        WednesdayMorningPanel.setPreferredSize(new Dimension(240, 321));
        WednesdayMorningPanel.setLayout(new BoxLayout(WednesdayMorningPanel, BoxLayout.Y_AXIS));

        WednesdayEveningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout WednesdayEveningPanelLayout = new javax.swing.GroupLayout(WednesdayEveningPanel);
        WednesdayEveningPanel.setLayout(WednesdayEveningPanelLayout);
        WednesdayEveningPanelLayout.setHorizontalGroup(
            WednesdayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        WednesdayEveningPanelLayout.setVerticalGroup(
            WednesdayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        WednesdayEveningPanel.setPreferredSize(new Dimension(240, 321));
        WednesdayEveningPanel.setLayout(new BoxLayout(WednesdayEveningPanel, BoxLayout.Y_AXIS));

        javax.swing.GroupLayout WednesdayIFrameLayout = new javax.swing.GroupLayout(WednesdayIFrame.getContentPane());
        WednesdayIFrame.getContentPane().setLayout(WednesdayIFrameLayout);
        WednesdayIFrameLayout.setHorizontalGroup(
            WednesdayIFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WednesdayIFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WednesdayIFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WednesdayIFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(WednesdayLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WednesdayMorningPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(WednesdayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WednesdayIFrameLayout.setVerticalGroup(
            WednesdayIFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WednesdayIFrameLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(WednesdayLabel)
                .addGap(18, 18, 18)
                .addComponent(WednesdayMorningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WednesdayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        MondayIFrame5.setVisible(true);

        MondayLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MondayLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MondayLabel2.setText("FRIDAY");

        FridayMorningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout FridayMorningPanelLayout = new javax.swing.GroupLayout(FridayMorningPanel);
        FridayMorningPanel.setLayout(FridayMorningPanelLayout);
        FridayMorningPanelLayout.setHorizontalGroup(
            FridayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FridayMorningPanelLayout.setVerticalGroup(
            FridayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        FridayMorningPanel.setPreferredSize(new Dimension(240, 321));
        FridayMorningPanel.setLayout(new BoxLayout(FridayMorningPanel, BoxLayout.Y_AXIS));

        FridayEveningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout FridayEveningPanelLayout = new javax.swing.GroupLayout(FridayEveningPanel);
        FridayEveningPanel.setLayout(FridayEveningPanelLayout);
        FridayEveningPanelLayout.setHorizontalGroup(
            FridayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        FridayEveningPanelLayout.setVerticalGroup(
            FridayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        FridayEveningPanel.setPreferredSize(new Dimension(240, 321));
        FridayEveningPanel.setLayout(new BoxLayout(FridayEveningPanel, BoxLayout.Y_AXIS));

        javax.swing.GroupLayout MondayIFrame5Layout = new javax.swing.GroupLayout(MondayIFrame5.getContentPane());
        MondayIFrame5.getContentPane().setLayout(MondayIFrame5Layout);
        MondayIFrame5Layout.setHorizontalGroup(
            MondayIFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayIFrame5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MondayIFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MondayIFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(MondayLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addComponent(FridayMorningPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(FridayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        MondayIFrame5Layout.setVerticalGroup(
            MondayIFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayIFrame5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MondayLabel2)
                .addGap(18, 18, 18)
                .addComponent(FridayMorningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(FridayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        MondayIFrame4.setVisible(true);

        TuesdayLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TuesdayLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TuesdayLabel2.setText("SATURDAY");

        SaturdayMorningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout SaturdayMorningPanelLayout = new javax.swing.GroupLayout(SaturdayMorningPanel);
        SaturdayMorningPanel.setLayout(SaturdayMorningPanelLayout);
        SaturdayMorningPanelLayout.setHorizontalGroup(
            SaturdayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        SaturdayMorningPanelLayout.setVerticalGroup(
            SaturdayMorningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        SaturdayMorningPanel.setPreferredSize(new Dimension(240, 321));
        SaturdayMorningPanel.setLayout(new BoxLayout(SaturdayMorningPanel, BoxLayout.Y_AXIS));

        SaturdayEveningPanel.setBackground(new java.awt.Color(19, 21, 25));

        javax.swing.GroupLayout SaturdayEveningPanelLayout = new javax.swing.GroupLayout(SaturdayEveningPanel);
        SaturdayEveningPanel.setLayout(SaturdayEveningPanelLayout);
        SaturdayEveningPanelLayout.setHorizontalGroup(
            SaturdayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        SaturdayEveningPanelLayout.setVerticalGroup(
            SaturdayEveningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        SaturdayEveningPanel.setPreferredSize(new Dimension(240, 321));
        SaturdayEveningPanel.setLayout(new BoxLayout(SaturdayEveningPanel, BoxLayout.Y_AXIS));

        javax.swing.GroupLayout MondayIFrame4Layout = new javax.swing.GroupLayout(MondayIFrame4.getContentPane());
        MondayIFrame4.getContentPane().setLayout(MondayIFrame4Layout);
        MondayIFrame4Layout.setHorizontalGroup(
            MondayIFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayIFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MondayIFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaturdayMorningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaturdayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TuesdayLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MondayIFrame4Layout.setVerticalGroup(
            MondayIFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MondayIFrame4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TuesdayLabel2)
                .addGap(18, 18, 18)
                .addComponent(SaturdayMorningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(SaturdayEveningPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jButton4.setBackground(new java.awt.Color(51, 57, 67));
        jButton4.setFont(new java.awt.Font("Noto Sans", 2, 17)); // NOI18N
        jButton4.setForeground(new java.awt.Color(154, 154, 154));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Name_Label.setAlignment(java.awt.Label.CENTER);
        Name_Label.setFont(new java.awt.Font("Renitah", 0, 48)); // NOI18N
        Name_Label.setForeground(new java.awt.Color(154, 154, 154));

        jLabel1.setFont(new java.awt.Font("Renitah", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(154, 154, 154));
        jLabel1.setText("Class:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(749, 749, 749))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(MondayIFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TuesdayIFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WednesdayIFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MondayIFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MondayIFrame5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MondayIFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(683, 683, 683)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TuesdayIFrame, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MondayIFrame, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(WednesdayIFrame)
                        .addComponent(MondayIFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MondayIFrame5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MondayIFrame4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel2.setBackground(new java.awt.Color(31, 35, 44));

        ButtonAdd.setBackground(new java.awt.Color(51, 57, 67));
        ButtonAdd.setFont(new java.awt.Font("Noto Sans", 2, 15)); // NOI18N
        ButtonAdd.setForeground(new java.awt.Color(154, 154, 154));
        ButtonAdd.setText("Add");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        ButtonDelete.setBackground(new java.awt.Color(51, 57, 67));
        ButtonDelete.setFont(new java.awt.Font("Noto Sans", 2, 15)); // NOI18N
        ButtonDelete.setForeground(new java.awt.Color(154, 154, 154));
        ButtonDelete.setText("Delete");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonEdit.setBackground(new java.awt.Color(51, 57, 67));
        ButtonEdit.setFont(new java.awt.Font("Noto Sans", 2, 15)); // NOI18N
        ButtonEdit.setForeground(new java.awt.Color(154, 154, 154));
        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(ButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        WindowChoice main = new WindowChoice();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        String classe = Name_Label.getText();
        System.out.println(classe);

        /**
         * java.awt.EventQueue.invokeLater(new Runnable() { public void run() {
         * new WindowTimetable_Add(classe).setVisible(true); } });*
         */
        WindowTimetable_Add windowTimetableAdd = new WindowTimetable_Add(classe, this);
        windowTimetableAdd.setVisible(true);

    }//GEN-LAST:event_ButtonAddActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        String classe = Name_Label.getText();
        System.out.println(classe);

        /**
         * java.awt.EventQueue.invokeLater(new Runnable() { public void run() {
         * new WindowTimetable_Add(classe).setVisible(true); } });*
         */
        WindowTimetable_Delete windowTimetableAdd = new WindowTimetable_Delete(classe, this);
        windowTimetableAdd.setVisible(true);
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        String classe = Name_Label.getText();
        System.out.println(classe);

        /**
         * java.awt.EventQueue.invokeLater(new Runnable() { public void run() {
         * new WindowTimetable_Add(classe).setVisible(true); } });*
         */
        WindowTimetable_Edit windowTimetableAdd = new WindowTimetable_Edit(classe, this);
        windowTimetableAdd.setVisible(true);
    }//GEN-LAST:event_ButtonEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /**
         * Create and display the form java.awt.EventQueue.invokeLater(new
         * Runnable() { public void run() { new Window_Main().setVisible(true);
         * } });
         */
    }

    public void setNameLabelText(String text) {
        // Assurez-vous que Name_Label est un composant déclaré dans votre classe
        Name_Label.setText(text);
    }

    public void getPlageFromDatabase(String className) {
        try {
            // Obtenez une connexion à la base de données
            Connection connection = Connector.getConnection();

            if (connection == null) {
                System.out.println("Erreur de connexion à la base de données.");
                return;
            }

            // Utilisez une requête SQL pour récupérer les informations de la plage horaire
            String query = "SELECT * FROM plage_horraire WHERE classe_associee = ? ORDER BY debut";

            try (PreparedStatement statement = connection.prepareStatement(query)) {
                statement.setString(1, className);

                System.out.println("Requête SQL : " + statement.toString());

                try (ResultSet resultSet = statement.executeQuery()) {
                    if (!resultSet.next()) {
                        System.out.println("Aucune plage horaire trouvée pour la classe : " + className);
                    } else {
                        // Créez des JLabel et les ajoutez à votre JPanel
                        do {
                            String matiere = resultSet.getString("matiere_associee");
                            String prof = resultSet.getString("prof_associee");
                            String salle = resultSet.getString("salle_associee");
                            String debut = resultSet.getString("debut");
                            Integer debut_int = Integer.parseInt(debut);
                            String fin = resultSet.getString("fin");
                            String date = resultSet.getString("date");
                            String duree = debut + "h" + " " + "-" + " " + fin + "h";

                            System.out.println("Matiere: " + matiere + ", Prof: " + prof + ", Salle: " + salle + ", Duree: " + duree);

                            Class cours = new Class(matiere, prof, salle, duree);

                            switch (date) {
                                case "Monday":
                                    if (debut_int < 13) {
                                        MondayMorningPanel.add(cours.getPanel());
                                    } else {
                                        MondayEveningPanel.add(cours.getPanel());
                                    }
                                    break;

                                case "Tuesday":
                                    if (debut_int < 13) {
                                        TuesdayMorningPanel.add(cours.getPanel());
                                    } else {
                                        TuesdayEveningPanel.add(cours.getPanel());
                                    }
                                    break;

                                case "Wednesday":
                                    if (debut_int < 13) {
                                        WednesdayMorningPanel.add(cours.getPanel());
                                    } else {
                                        WednesdayEveningPanel.add(cours.getPanel());
                                    }
                                    break;

                                case "Thursday":
                                    if (debut_int < 13) {
                                        ThursdayMorningPanel.add(cours.getPanel());
                                    } else {
                                        ThursdayEveningPanel.add(cours.getPanel());
                                    }
                                    break;

                                case "Friday":
                                    if (debut_int < 13) {
                                        FridayMorningPanel.add(cours.getPanel());
                                    } else {
                                        FridayEveningPanel.add(cours.getPanel());
                                    }
                                    break;

                                case "Saturday":
                                    if (debut_int < 13) {
                                        SaturdayMorningPanel.add(cours.getPanel());
                                    } else {
                                        SaturdayEveningPanel.add(cours.getPanel());
                                    }
                                    break;

                                // Ajoutez d'autres cas pour les autres jours si nécessaire
                                default:
                                    break;
                            }

                        } while (resultSet.next());
                    }
                }
            }

            // Fermez la connexion à la base de données
            connection.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erreur SQL : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void refreshWindow() {
        MondayMorningPanel.removeAll();
        MondayEveningPanel.removeAll();
        TuesdayEveningPanel.removeAll();
        TuesdayMorningPanel.removeAll();
        WednesdayMorningPanel.removeAll();
        WednesdayEveningPanel.removeAll();
        ThursdayEveningPanel.removeAll();
        ThursdayMorningPanel.removeAll();
        FridayEveningPanel.removeAll();
        FridayMorningPanel.removeAll();
        SaturdayEveningPanel.removeAll();
        SaturdayMorningPanel.removeAll();
        getPlageFromDatabase(Name_Label.getText());
        System.out.println("The Main window was refreshed");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JPanel FridayEveningPanel;
    private javax.swing.JPanel FridayMorningPanel;
    private javax.swing.JPanel MondayEveningPanel;
    private javax.swing.JInternalFrame MondayIFrame;
    private javax.swing.JInternalFrame MondayIFrame3;
    private javax.swing.JInternalFrame MondayIFrame4;
    private javax.swing.JInternalFrame MondayIFrame5;
    private javax.swing.JLabel MondayLabel;
    private javax.swing.JLabel MondayLabel2;
    private javax.swing.JPanel MondayMorningPanel;
    private java.awt.Label Name_Label;
    private javax.swing.JPanel SaturdayEveningPanel;
    private javax.swing.JPanel SaturdayMorningPanel;
    private javax.swing.JPanel ThursdayEveningPanel;
    private javax.swing.JPanel ThursdayMorningPanel;
    private javax.swing.JPanel TuesdayEveningPanel;
    private javax.swing.JInternalFrame TuesdayIFrame;
    private javax.swing.JLabel TuesdayLabel;
    private javax.swing.JLabel TuesdayLabel1;
    private javax.swing.JLabel TuesdayLabel2;
    private javax.swing.JPanel TuesdayMorningPanel;
    private javax.swing.JPanel WednesdayEveningPanel;
    private javax.swing.JInternalFrame WednesdayIFrame;
    private javax.swing.JLabel WednesdayLabel;
    private javax.swing.JPanel WednesdayMorningPanel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
